nelmio_api_doc:
    documentation:
        info:
            title: Codemotion
            description: api docs
            version: 1.0.0
    areas: # to filter documented areas
        default:
            disable_default_routes: true