version: '3.5'

services:
  app:
    env_file:
      - ../project/.env.local
    build: docker/php
    working_dir: ${WORKING_DIR}
    volumes:
      - ./:${WORKING_DIR}
    container_name: clubforce_app

  webserver:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:80
    working_dir: ${WORKING_DIR}
    volumes:
      - ./:${WORKING_DIR}
      - ./docker/nginx/config/conf.d/:/etc/nginx/conf.d/
    links:
      - app
    container_name: clubforce_webserver

